### ISSUE TITLE
Mage registry key "_singleton/turpentine/observer_esi" already exists

### ISSUE THREAD

**Issue by mnightwalker** [nexcess/magento-turpentine#1211]
Facing this issue even after I deleted all the traces of this extension from my cpanel:

There has been an error processing your request
Mage registry key "_singleton/turpentine/observer_esi" already exists

Trace:
#0 /home4/arabianglitz/public_html/app/Mage.php(223): Mage::throwException('Mage registry k...')
#1 /home4/arabianglitz/public_html/app/Mage.php(477): Mage::register('_singleton/turp...', false)
#2 /home4/arabianglitz/public_html/includes/src/__default.php(22147): Mage::getSingleton('turpentine/obse...')
#3 /home4/arabianglitz/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_fron...', Array)
#4 /home4/arabianglitz/public_html/includes/src/__default.php(18236): Mage::dispatchEvent('controller_fron...', Array)
#5 /home4/arabianglitz/public_html/includes/src/__default.php(21575): Mage_Core_Controller_Varien_Front->init()
#6 /home4/arabianglitz/public_html/includes/src/__default.php(21924): Mage_Core_Model_App->_initFrontController()
#7 /home4/arabianglitz/public_html/includes/src/__default.php(21176): Mage_Core_Model_App->getFrontController()
#8 /home4/arabianglitz/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#9 /home4/arabianglitz/public_html/index.php(83): Mage::run('', 'store')
#10 {main}

Error log record number: 439899099391

**Comment by mnightwalker** [comment]
Issue resolved I have followed this: http://cpanelplesk.com/how-to-clear-the-magento-cache/#comment-64274
