### ISSUE TITLE
__construct(): Unknown or bad timezone

### ISSUE THREAD

**Issue by craigcarnell** [nexcess/magento-turpentine#1486]
Magento EE 1.14.3.8

Appears in checkout, results in order failure screen, but the order goes through successfully? Doesn't happen all the time.

```
a:5:{i:0;s:55:"DateTimeZone::__construct(): Unknown or bad timezone ()";i:1;s:2246:"#0 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/code/local/Mage/Core/Model/Session/Abstract/Varien.php(134): DateTime->__wakeup()
#1 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/code/local/Mage/Core/Model/Session/Abstract/Varien.php(228): Mage_Core_Model_Session_Abstract_Varien->start()
#2 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/code/core/Mage/Core/Model/Session/Abstract.php(84): Mage_Core_Model_Session_Abstract_Varien->init()
#3 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/code/community/Nexcessnet/Turpentine/Model/Core/Session.php(26): Mage_Core_Model_Session_Abstract->init()
#4 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/code/core/Mage/Core/Model/Config.php(1357): Nexcessnet_Turpentine_Model_Core_Session->__construct()
#5 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/Mage.php(471): Mage_Core_Model_Config->getModelInstance()
#6 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/Mage.php(485): Mage::getModel()
#7 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/code/core/Mage/Core/Controller/Varien/Action.php(493): Mage::getSingleton()
#8 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/code/core/Mage/Core/Controller/Front/Action.php(69): Mage_Core_Controller_Varien_Action->preDispatch()
#9 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Core_Controller_Front_Action->preDispatch()
#10 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch()
#11 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match()
#12 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#13 /var/www/vhosts/magento-capistrano/releases/20180327144341/app/Mage.php(692): Mage_Core_Model_App->run()
#14 /var/www/vhosts/magento-capistrano/releases/20180327144341/index.php(112): Mage::run()
#15 {main}";s:3:"url";s:36:"/a-product-page";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:10:"uk_default";}
```

**Comment by EvanRijn** [comment]
What is the output of;

SELECT * FROM `core_config_data` WHERE `path` = 'general/locale/timezone'

**Comment by craigcarnell** [comment]
@EvanRijn 

```
6	default	0	general/locale/timezone	Europe/London
```

**Comment by miguelbalparda** [comment]
I've seen multiple reports of this, probably not related to Turpentine. A good start might be [here](https://magento.stackexchange.com/questions/135188/my-magento-2-website-is-crashed-unknown-or-bad-timezone-error) even if the Q is for M2. Closing for now, feel free to reopen.
