### ISSUE TITLE
Errors in admin area

### ISSUE THREAD

**Issue by Springerton** [nexcess/magento-turpentine#5]
I have some bugs in admin area.
In System > Varnish Management don't work functions. No one.

After click on any button, I'm redirecting to Magento error page:

"There has been an error processing your request
Exception printing is disabled by default for security reasons.

Error log record number: 837656914520"

Inf file:

```
a:5:{i:0;s:106:"Got unexpected response code from Varnish: 107
<removed>

Authentication required.
";i:1;s:2565:"#0 /magento/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php(406): Mage::throwException('Got unexpected ...')
#1 PATHTOMAGENTO/magento/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php(299): Nexcessnet_Turpentine_Model_Varnish_Admin_Socket->_command('auth', 200, '9629ca4046e3c5c...')
#2 PATHTOMAGENTO/magento/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php(329): Nexcessnet_Turpentine_Model_Varnish_Admin_Socket->_connect()
#3 PATHTOMAGENTO/magento/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php(440): Nexcessnet_Turpentine_Model_Varnish_Admin_Socket->_write('help')
#4 PATHTOMAGENTO/magento/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin/Socket.php(226): Nexcessnet_Turpentine_Model_Varnish_Admin_Socket->_determineVersion()
#5 PATHTOMAGENTO/magento/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin.php(135): Nexcessnet_Turpentine_Model_Varnish_Admin_Socket->getVersion()
#6 PATHTOMAGENTO/magento/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin.php(44): Nexcessnet_Turpentine_Model_Varnish_Admin->getConfigurator()
#7 PATHTOMAGENTO/magento/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Admin.php(33): Nexcessnet_Turpentine_Model_Varnish_Admin->flushUrl('.*')
#8 PATHTOMAGENTO/magento/app/code/community/Nexcessnet/Turpentine/controllers/Varnish/ManagementController.php(48): Nexcessnet_Turpentine_Model_Varnish_Admin->flushAll()
#9 PATHTOMAGENTO/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(419): Nexcessnet_Turpentine_Varnish_ManagementController->flushAllAction()
#10 PATHTOMAGENTO/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('flushAll')
#11 PATHTOMAGENTO/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 PATHTOMAGENTO/magento/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 PATHTOMAGENTO/magento/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#14 PATHTOMAGENTO/magento/index.php(87): Mage::run('', 'store')
#15 {main}";s:3:"url";s:90:"/magento/index.php/admin/varnish_management/flushAll/key/<removed>/";s:11:"script_name";s:18:"/magento/index.php";s:4:"skin";s:5:"admin";}
```

**Comment by beckindesigns** [comment]
Here is what worked for me and I don't see this answer anywhere.

In my case it was a turpentine setting. I used the backdoor to get into the admin area by going to the downloader page (yoursite.com/downloader) and logging in. After that, I changed **_System > Configurations > Turpentine > Varnish Options > General Options > Use VCL fix_** to "disabled".

"When Enable is selected, a VCL fix will be used to prevent formKey issues. If Disable is selected, an observer will be used."

It appears the observer did the trick. Also, I am not using an override of the `app/code/local/Mage/Core/Model/Session.php` file.
