### ISSUE TITLE
exception 'Zend_Uri_Exception' with message 'Invalid URI supplied' in /var/www/vhosts/magento-capistrano/releases/20140815084233/lib/Zend/Uri/Http.php:156

### ISSUE THREAD

**Issue by craigcarnell** [nexcess/magento-turpentine#602]
```
2014-08-15T08:53:54+00:00 ERR (uk_default): /turpentine/esi/getBlock/method/ajax/access/private/ttl/0/hmac/e53c498b043da05d6807ac0d1636450b6bcad8a3fdcf3424d93350705ef48eb1/data/-XSCO0rgxv8Z6H4vzOfkywZ5DKRI0sSbKlTcIrUBK2LhsPr-Q2LQzFRicnTzAbsFNnfxmXsaI8Tiz9ILhQPxUsLMUb4ULmWxfg32H0tnnsuwzcSYOKoSfUHXFR3QSHeR400i-PnAvXDVexMUyfznnhRmy5zV5CCf536LNkAOyC9RT6ahZYTo67A0SppMUAY0cBzflcwJQJru3s7yEVLZMySsA3XWPWBZIPLafKXIaG-TXlDWt7yWuaIn2Ok3CT4e4yWbxzoKAtM36DQPbTozzERLw6byg0JER1-wdGvv80.Q8MVYRKFroszkfDxIQc5nRQWQ6o3tMM-JX8IIw3DF4g==/ 
REQUEST: -
TIME: 0.072332s
ADDRESS: xxx
USER AGENT: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0
FILE: 20140815084233/app/code/community/Nexcessnet/Turpentine/Model/Dummy/Request.php:50

exception 'Zend_Uri_Exception' with message 'Invalid URI supplied' in /var/www/vhosts/magento-capistrano/releases/20140815084233/lib/Zend/Uri/Http.php:156
Stack trace:
#0 /var/www/vhosts/magento-capistrano/releases/20140815084233/lib/Zend/Uri.php(143): Zend_Uri_Http->__construct()
#1 /var/www/vhosts/magento-capistrano/releases/20140815084233/lib/Zend/Controller/Request/Http.php(113): Zend_Uri::factory()
#2 /var/www/vhosts/magento-capistrano/releases/20140815084233/app/code/community/Nexcessnet/Turpentine/Model/Dummy/Request.php(44): Zend_Controller_Request_Http->__construct()
#3 /var/www/vhosts/magento-capistrano/releases/20140815084233/app/code/community/Nexcessnet/Turpentine/Helper/Esi.php(184): Nexcessnet_Turpentine_Model_Dummy_Request->__construct()
#4 /var/www/vhosts/magento-capistrano/releases/20140815084233/app/code/community/Nexcessnet/Turpentine/controllers/EsiController.php(95): Nexcessnet_Turpentine_Helper_Esi->getDummyRequest()
#5 /var/www/vhosts/magento-capistrano/releases/20140815084233/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Nexcessnet_Turpentine_EsiController->getBlockAction()
#6 /var/www/vhosts/magento-capistrano/releases/20140815084233/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch()
#7 /var/www/vhosts/magento-capistrano/releases/20140815084233/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match()
#8 /var/www/vhosts/magento-capistrano/releases/20140815084233/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/vhosts/magento-capistrano/releases/20140815084233/app/Mage.php(684): Mage_Core_Model_App->run()
#10 /var/www/vhosts/magento-capistrano/releases/20140815084233/index.php(112): Mage::run()
#11 {main}
```

**Comment by aricwatson** [comment]
@craigcarnell did you ever find a cause/resolution for this?

**Comment by Stasevi4** [comment]
Hello! I get same error on catalogsearch
TURPENTINE: Bad URI given to dummy request: http://www.xxxxx.com/catalogsearch/advanced/result/?author=Р‘СѓРЅРёРјРѕРІРёС‡ Р•. . How can  avoid this issue ?

**Comment by aricwatson** [comment]
@Stasevi4 The 'Bad URI' error is generated when Turpentine tries to use Mage_Core_Controller_Request_Http to construct the request and fails. In this case, I'm guessing Magento does not like some of the characters in the author param of the URI being passed. Does it work with other URIs?

**Comment by Stasevi4** [comment]
We have a lot of links similar with Russian characters but they work.  I try to click same link and no errors. Can it be customer configuration encoding ?

**Comment by jkenneydaniel** [comment]
We're seeing this error in our production environment:

http://www.example.com/catalogsearch/result/index/form_key/{{form_key_esi_placeholder}}/?q=keywords

Currently trying to debug this issue as well - assuming it's because of the form_key_esi_placeholder? Not sure though - gonna have to look into it more (just started looking today).

**Comment by aricwatson** [comment]
@jkenneydaniel what version of Varnish are you using?

**Comment by whgoods** [comment]
@aricwatson We're using Varnish 3.0.5

**Comment by aricwatson** [comment]
Can you verify that you're starting Varnish with this parameter: `-p esi_syntax=0x2` ?

**Comment by elvin-vaimo** [comment]
this was also an issue in #238

**Comment by luigifab** [comment]
For us, I have `if (!empty($uri)) $uri = str_replace('|', '%7C', $uri);` to fix the same problem:

https://github.com/nexcess/magento-turpentine/blob/c670a492a18cf495d87699e0dbd712ad03fd84ad/app/code/community/Nexcessnet/Turpentine/Model/Dummy/Request.php#L40-L46
